#!/bin/bash -login
 
#PBS -l walltime=05:00:00
#PBS -l nodes=1:ppn=10 
#PBS -l mem=80gb
#PBS -j oe
#PBS -N directory_muscle
 
### load necessary modules, e.g.
module load MUSCLE
module load BLAST+
module load CDHIT

### make necessary directorys for file storage
	#mkdir /mnt/home/wrigh655/Documents/KiVD/fastafiles
	#mkdir /mnt/home/wrigh655/Documents/KiVD/blastpresults
	#mkdir /mnt/home/wrigh655/Documents/KiVD/CDHITs
	#mkdir /mnt/home/wrigh655/Documents/KiVD/MUSLCEreulsts
	#mkdir /mnt/home/wrigh655/Documents/KiVD/PSSMs
 
#Command to run all files in fasta database
#numfiles=(*)
#numfiles=${#numfiles[@]}
 #for ((i=0;i<numfiles;i++))
#do

	### change to the working directory where your code is located
	cd /mnt/home/wrigh655/Documents/KiVD/fastafiles


	### run blast p
	blastp -query /mnt/home/wrigh655/Documents/KiVD/1OZF.fasta -db nr -evalue 0.0001 -max_target_seqs 20000 -out /mnt/home/wrigh655/Documents/KiVD/blastpresults/1OZF_blast.fasta 

	### run CD-HIT
	cd-hit -i /mnt/home/wrigh655/Documents/KiVD/blastpresults/1OZF_blast.fasta -o /mnt/home/wrigh655/Documents/KiVD/CDHITs/CD_Hit_1OZF.fasta

	### run MUSCLE
	muscle -in /mnt/home/wrigh655/Documents/KiVD/CDHITs/CD_Hit_1OZF.fasta -out /mnt/home/wrigh655/Documents/KiVD/MUSCLEresults/MSA_1OZF.fasta  

	### run PSI-BLAST
	psiblast -subject /mnt/home/wrigh655/Documents/KiVD/fastafiles/1OZF -in_msa /mnt/home/wrigh655/Documents/KiVD/MUSCLEresults/MSA_1OZF.fasta -out_ascii_pssm /mnt/home/wrigh655/Documents/KiVD/PSSMs/PSSM_1OZF.pssm > 1OZF_pssm.log
#done
